#!/bin/bash

echo "Running git pre-push hook"

moduleName="store"

./gradlew ":$moduleName:ktlint" 

RESULT=$?

# return 1 exit code if running checks fails
if [ $RESULT -ne 0 ]; then
  ./gradlew ":$moduleName:ktlintFormat"
  exit 1
else
  exit 0
fi
